name: Build and Push Docker Container to Docker Hub
on:
  push: 
    branches: [ 'master' ]
env:
  DOCKER_BUILDKIT: 1
jobs:
  build_and_push_docker_images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker Image to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: markhobson/sqlpackage:${{ github.sha }}
          cache-from: type=registry,ref=markhobson/sqlpackage:buildcache # Remove if you do not need cache (I suspect you will probably not)
          cache-to: type=registry,ref=markhobson/sqlpackage:buildcache,mode=max # Remove if you do not need cache
